version: '3'
services:
  pg:
    image: postgres:15.0
    hostname: pg
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - ./vksearch:/app
    restart: always

  web:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - ./.env
    expose:
      - "8000"
    volumes:
      - ./vksearch:/app/vksearch
    depends_on:
      - pg
      - rabbitmq

  celery:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    command: celery -A vksearch worker -c 6 --loglevel=info
    volumes:
      - ./vksearch:/app/vksearch
    env_file:
      - ./.env
    depends_on:
      - web
      - rabbitmq

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    command: celery --broker=amqp://guest@rabbitmq:5672// flower --broker_api=http://guest:guest@rabbitmq:15672/api//
    depends_on:
      - rabbitmq


volumes:
  pg-data:


