# Generated by Django 4.1.3 on 2022-11-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vkgroup", "0004_alter_communitytype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="description",
            field=models.TextField(default="", null=True),
        ),
    ]
