# Generated by Django 4.1.3 on 2022-11-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vkgroup", "0007_alter_audienceprofile_sex_alter_community_age_vk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="community",
            name="site",
            field=models.CharField(default="", max_length=128),
        ),
    ]
