# Generated by Django 4.1.3 on 2022-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vkgroup", "0008_alter_community_name_alter_community_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="site",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
