# Generated by Django 4.1.3 on 2022-11-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vkgroup", "0009_alter_community_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="members",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
