# Generated by Django 4.1.3 on 2022-11-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vkgroup", "0010_alter_community_members_alter_community_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="members",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
