# Generated by Django 4.1.3 on 2022-11-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vkgroup", "0013_alter_community_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="deactivated",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="community",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
