# Generated by Django 4.1.3 on 2022-11-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vkgroup", "0019_alter_community_description_alter_community_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
