# Generated by Django 4.1.3 on 2022-11-18 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vkgroup", "0023_alter_agerange_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audience",
            name="community",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vkgroup.community",
            ),
        ),
        migrations.AlterField(
            model_name="audience",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vkgroup.audienceprofile",
            ),
        ),
        migrations.AlterField(
            model_name="audienceprofile",
            name="age_range",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vkgroup.agerange",
            ),
        ),
        migrations.AlterField(
            model_name="audienceprofile",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vkgroup.country",
            ),
        ),
    ]
